name: CI

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest-alpine
    steps:
      - name: Download source code
        uses: actions/checkout@v3
      - name: Format
        run: "crystal tool format --check"
      - name: Run tests
        run: "crystal spec --warnings all --error-on-warnings"
